### ISSUE TITLE
Replace in hidden files in MacOS not working?

### ISSUE THREAD

**Issue by Ronald-Diemicke** [adamreisnz/replace-in-file#103]
I'm trying to do a replace in hidden files (starting with a '.') but it's not working. Any ideas?

**Comment by adamreisnz** [comment]
Do you mean they aren't being found? Probably need to work on your regex for file matching.

**Comment by adamreisnz** [comment]
Closing this one off now, but let me know if you still run into issues.

**Comment by butaca** [comment]
I'm experience the same issue on macOS

**Comment by butaca** [comment]
The problem is that by default glob is ignoring paths starting with dots. This can be changed with this configuration: https://www.npmjs.com/package/replace-in-file#specify-glob-configuration

```
const options = {
  glob: {
    dot: true,
  },
}
```
