### ISSUE TITLE
Recursive lookup not working

### ISSUE THREAD

**Issue by BinaryShrub** [adamreisnz/replace-in-file#104]
```
replace({
        files: modulePath + '**/*template*',
        from: new RegExp(`%_${key}_%`, 'g'),
        to: value
      })
```

the above command does not traverse more than than a single folder depth. I would expect it to search every sub folder of my modulePath like it would with `ls **/*template*`

**Comment by BinaryShrub** [comment]
I ended up using https://www.npmjs.com/package/find

```
await replace({
        files: find.fileSync(/template/g, modulePath),
        from: new RegExp(`%_${key}_%`, 'g'),
        to: value
      })
```

**Comment by adamreisnz** [comment]
The package uses `glob` underneath to find files, so whichever files are returned by glob, we process them. You can [pass specific configuration to glob](https://github.com/adamreisnz/replace-in-file#specify-glob-configuration) as well, which may affect how it handles recursivity and sub folders.

But glad to see you found a work around anyway.
