### ISSUE TITLE
Move from yargs to minimist

### ISSUE THREAD

**Issue by DomiR** [adamreisnz/replace-in-file#105]
You are only using the parsing part of yargs which is also handled by minimist but yargs adds cliui and a bunch of other unnecessary deps...

Would you be open to a PR?

**Comment by adamreisnz** [comment]
Hmm, do you notice any negative side effects as a result of having yargs though? Does it impact your build time or run time?

I am reluctant to switch packages just for the sake of it, so would like to hear from some more people what they think first before actioning this.

We've been using yargs in most of our packages for nearly as long as I can remember and never had any issues though.

But if there's a consensus that we could switch to minimist then I'd be open to a PR.

**Comment by adamreisnz** [comment]
Closing this off for now, but any feedback is still welcome.
