### ISSUE TITLE
cwd option in root of the config not used yet

### ISSUE THREAD

**Issue by akaguny** [adamreisnz/replace-in-file#115]
https://github.com/adamreisnz/replace-in-file/blob/f94e466cb05942934a6f654ab100821cb4166ac5/lib/helpers/parse-config.js#L17
maybe delete it?

**Comment by adamreisnz** [comment]
The `cwd` option is used, see #56 and also https://github.com/adamreisnz/replace-in-file#making-replacements-on-network-drives

**Comment by akaguny** [comment]
This parameter only works for the sync mode?
But why do not use config.glob.cwd?
We can delete useless code)
```
  //Extract relevant config
  const {ignore, disableGlobs, glob: globConfig, cwd} = config;

  //Not using globs?
  if (disableGlobs) {
    return patterns;
  }

  //Prepare glob config
  const cfg = Object.assign({ignore}, globConfig, {nodir: true});

  //Append CWD configuration if given (#56)
  //istanbul ignore if
  if (cwd) {
    cfg.cwd = cwd;
  }
```

```
  //Extract relevant config
  const {ignore, disableGlobs, glob: globConfig} = config;

  //Not using globs?
  if (disableGlobs) {
    return patterns;
  }

  //Prepare glob config
  const cfg = Object.assign({ignore}, globConfig, {nodir: true});
```

or in another way for better developer experience we can use config.cwd in all cases)

**Comment by adamreisnz** [comment]
Sorry, I'm afraid I don't follow. The `cwd` path is not passed on to glob.
It is prefixed for all paths as follows:

```
//Prefix each path with CWD if given (#56)
  //istanbul ignore if
  if (cwd) {
    return flattened.map(path => `${cwd}${path}`);
  }
```

I believe there was a reason for this, and it didn't work if you pass it into globs. See #56 for the rationale. This is not useless code as far as I am aware.
