### ISSUE TITLE
fix glob config is not usefull

### ISSUE THREAD

**Issue by akaguny** [adamreisnz/replace-in-file#116]
https://github.com/adamreisnz/replace-in-file/blob/f94e466cb05942934a6f654ab100821cb4166ac5/lib/helpers/parse-config.js#L31
because glob config has default value, is empty object. Right side of condition not execute anytime

**Comment by adamreisnz** [comment]
Right side of the code will execute when you pass in for example {glob: null} as config.
The defaults are only applied later on in the code, on line 66.
