### ISSUE TITLE
replace multiple values with different replacements in different files

### ISSUE THREAD

**Issue by akaguny** [adamreisnz/replace-in-file#119]
I have config for my replacement:
```typesctript
type UpdateVersionsConfig = {
  someBuisnessLogicProps?: any;
  files: Array<UpdateVersionsFileReplaceConfig>;
};

type UpdateVersionsFileReplaceConfig = {
  path: Array<string>;
  replace: Array<{
    from: string;
    to: string;
  }>;
};
```
In my case for different files need different replacements.
Now i need something like for normalize
```
{
        files: config.files.flatMap(({ path }) => path),
        from: config.files
          .flatMap(({ replace }) => replace)
          .flatMap(({ from }) => from),
        to: config.files
          .flatMap(({ replace }) => replace)
          .flatMap(({ to }) => to),
        glob: {
          absolute: true,
          cwd: mayBeCloneGitRepository.value,
        },
      }
```
but in can create bugs because in normalize i simple concat all `UpdateVersionsFileReplaceConfig`.
In this way i have a bug with this conditions:
* similar content in files
* different replacements for similar content
I see a workaround:
Execute multiply "replaceInFile" function with needed parameters. But i dont like it.

**Comment by adamreisnz** [comment]
To the best of my knowledge this is not currently possible or supported.

You can do multiple different replacements, https://github.com/adamreisnz/replace-in-file#multiple-values-with-different-replacements, but on the same files only.

I think the workaround is currently the only option.

**Comment by akaguny** [comment]
@adamreisnz , maybe its for next major realize or minor improvement?

**Comment by adamreisnz** [comment]
Sure, open to a PR with ideas on how to implement it

**Comment by akaguny** [comment]
now i have no enough time for the research for create solution for single run replace in file for different replacements in different files (optimization)
correct workaround, someone may be usefully
```js
const normalizes = {
  from: function normalizeFroms(
    configFiles: UpdateVersionsFileReplaceConfig
  ): Array<string | RegExp> {
    return configFiles.replace.flatMap(({ from }) => from);
  },
  to: function normalizeFroms(
    configFiles: UpdateVersionsFileReplaceConfig
  ): Array<string> {
    return configFiles.replace.flatMap(({ to }) => to);
  },
};

export const normalizeConfigs = (
  config,
  globOptions: { cwd: string; absolute: boolean }
): Array<ReplaceInFileConfig> => {
  const normalizedConfigs = [];
  for (const configFile of config.files) {
    normalizedConfigs.push({
      files: configFile.path,
      from: normalizes.from(configFile),
      to: normalizes.to(configFile),
      ...(configFile.encoding ? { encoding: configFile.encoding } : {}),
      glob: { ...globOptions },
    });
  }
  return normalizedConfigs;
};
```
and run replace file function multiply with arguments =)
