### ISSUE TITLE
Feature Request: Use filename in `to` field

### ISSUE THREAD

**Issue by mesqueeb** [adamreisnz/replace-in-file#121]
I'd love to be able to insert the filename when replacing something.

Eg. the example below would
1. take a regex that matches the entire file contents
2. replace it with the same content, but add an extra line with the filename

```js
const options = {
  from: /([\S\s]+)/,
  to: (file) => `${file.name}\n$1`,
}
```

**Comment by adamreisnz** [comment]
This is already possible: https://github.com/adamreisnz/replace-in-file#using-callbacks-for-to

> This callback provides for an extra argument above the String replace method, which is the name of the file in which the replacement is being performed. 

```js
const options = {
  files: 'path/to/file',
  from: /SomePattern[A-Za-z-]+/g,
  to: (...args) => args.pop(), //The last argument is the filename
};
```
