### ISSUE TITLE
Incorrect TypeScript definition for `ToCallback`

### ISSUE THREAD

**Issue by smithki** [adamreisnz/replace-in-file#123]
The `ToCallback` type definition indicates the second argument should be `string`, but actually the function takes the same shape as a [`String.prototype.replace` replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter).

Unfortunately, there's not a surefire way to type a replacer as it's not statically analyzable. Instead of passing all arguments to the `ToCallback` function, it would be more sound (in my opinion), to do something like this:

```
contents.replace(item, (...args) => replacement(args[0], args.pop()));
```

**Comment by roydukkey** [comment]
I believe this was incorrectly closed.

> Unfortunately, there's not a surefire way to type a replacer as it's not statically analyzable. Instead of passing all arguments to the ToCallback function, it would be more sound (in my opinion), to do something like this:
> 
> ```
> contents.replace(item, (...args) => replacement(args[0], args.pop()));
> ```

The type still doesn't satisfy all the possibilities.
