### ISSUE TITLE
Something really wrong here

### ISSUE THREAD

**Issue by rikyperdana** [adamreisnz/replace-in-file#127]
![Screenshot from 2020-09-15 20 41 08](https://user-images.githubusercontent.com/11875540/93217922-d2f8df00-f793-11ea-80ea-3edad856622d.png)

Whenever a replacement occurs, the edited files came with unknown closing parentheses or brackets
It made the library unusable, please help

**Comment by adamreisnz** [comment]
This package has 217k weekly downloads, if it would be unusable I think we would have seen more issues show up here.

Also, without seeing any configuration that you are using, I am unable to provide any assistance. Feel free to re-open when you have a code sample that I can use to reproduce your issue.
