### ISSUE TITLE
How to use it with Gulp?

### ISSUE THREAD

**Issue by brendan8c** [adamreisnz/replace-in-file#136]
I want to replace all lines `'img/sprite.png'` with on strings `'../img/sprite.png'`
The lines are in the file (`style.min.css`)
I am doing something wrong... I have errors, please help me

![0](https://user-images.githubusercontent.com/61526280/120731005-5ce80400-c4eb-11eb-8a11-5d546cd4efc1.png)
```JavaScript
function fixSprites() {
    const results = replace.sync({
        files: config.build.style + '/style.min.css',
        from: 'img/sprite.png',
        to: '../img/sprite.png',
        countMatches: true,
    })
    return src(config.build.style + '/style.min.css')
        .pipe(replace(results))
}

exports.fixSprites = fixSprites()
```

**Comment by adamreisnz** [comment]
This is a standalone Node module, I don't think you can just use it in Gulp like that. Instead, you need to wrap it in a helper function like so:

```
module.exports = function updateRedirects(done) {
  replaceInFile({
    files: path.join(build.DEST_ASSETS, '_redirects'),
    from: /%API_BASE_URL%/g,
    to: config.api.baseUrl,
  }, done);
};
```

And then use it in Gulp like with `gulp.series` or `gulp.parallel`

**Comment by brendan8c** [comment]
I rewrote it as you said.
It worked but only once.
I want to say that the replacement was successful, but only one line in the file changed, the rest remained the same.
What can I do to make it replace all the lines it finds?
![2021-06-05 15_39_27-● gulpfile js - start_gulp - Visual Studio Code  Не поддерживается](https://user-images.githubusercontent.com/61526280/120892006-91a3aa80-c614-11eb-9894-6849d2240a88.png)

```JavaScript
function updateRedirects(done) {
    replace({
        files: config.build.style + '/style.min.css',
        from: 'img/sprite.png',
        to: '../img/sprite.png',
    }, done);
}

exports.build = series(updateRedirects)
```

**Comment by brendan8c** [comment]
This is the out of the box gulp solution
Replace all lines of a similar type with others. 
Example: replace  **img/sprite.png** with **../img/sprite.png**

![2021-06-06 02_02_30-gulpfile js - start_gulp - Visual Studio Code  Не поддерживается](https://user-images.githubusercontent.com/61526280/120907564-508ab500-c66b-11eb-9a22-92deb80f1dbf.png)

```JavaScript
const { series } = require('gulp')
const replace = require('replace-in-file')

function updateRedirects(done) {
    replace({
        files: 'build/css/style.min.css',
        from: /img\/sprite.png/g, // img/sprite.png – Replace this.
        to: '../img/sprite.png', // ../img/sprite.png – Replace with this.
        countMatches: true,
    }, done)
}

exports.build = series(updateRedirects) // Start
```

**Comment by brendan8c** [comment]
> Это автономный модуль Node, я не думаю, что вы можете просто так использовать его в Gulp. Вместо этого вам нужно обернуть его вспомогательной функцией следующим образом:
> 
> ```
> module.exports = function updateRedirects(done) {
>   replaceInFile({
>     files: path.join(build.DEST_ASSETS, '_redirects'),
>     from: /%API_BASE_URL%/g,
>     to: config.api.baseUrl,
>   }, done);
> };
> ```
> 
> А затем используйте его в Gulp, например, с помощью `gulp.series`или`gulp.parallel`

Tell me can I do this with any node.js plugin?
I've tried doing something similar with other node.js plugins but it didn't work.
What might it depend on? What do I need to know to adopt any other node.js plugin for gulp?
I am asking you because I believe you are an expert in this area.

**Comment by adamreisnz** [comment]
Yes, just make your own file and import it as a plugin in your main gulpfile.

E.g.

```
const updateRedirects = require('./build/tasks/update-redirects');

gulp.task('build', gulp.series(
  clean,
  gulp.parallel(
    gulp.series(
      copyAssets,
      updateHeaders,
      updateRedirects,
      createVersionFile
    ),
    buildConfig,
    buildAppJs,
    buildAppCss,
    buildLibJs,
  ),
  buildIndex,
  updateServiceWorker
));
```

**Comment by brendan8c** [comment]
> Да, просто создайте свой собственный файл и импортируйте его как плагин в свой основной файл gulp.
> 
> Например
> 
> ```
> const updateRedirects = require('./build/tasks/update-redirects');
> 
> gulp.task('build', gulp.series(
>   clean,
>   gulp.parallel(
>     gulp.series(
>       copyAssets,
>       updateHeaders,
>       updateRedirects,
>       createVersionFile
>     ),
>     buildConfig,
>     buildAppJs,
>     buildAppCss,
>     buildLibJs,
>   ),
>   buildIndex,
>   updateServiceWorker
> ));
> ```

It turned out to be more difficult than I thought...
When you have free time, please write an example of how this is done. For example with any of these plugins (uglify-js or clean-css or html-minifier).
I will wait as long as necessary.
I've looked at a lot of information these days, but it's difficult to combine everything with your example.
I want to see how this is implemented and study.
And then, looking at an example, try it yourself with another plugin.
I would be grateful if at least you showed it.
I have been asking a similar question on StackOverflow but no one answered there.
Sorry for the offtopic
