### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by RyanZim** [adamreisnz/replace-in-file#15]
Hey, I just noticed that you added a CLI. I was wondering if you would consider supporting a config file to contain the `from` & `to` options.

My use-case: I replace an HTML comment with my analytics tracking code. The tracking code is multi-line, so I can't inline it in the command. If we had a config file, we could do something like:

```js
module.exports = {
  from: '<!-- replace me -->',
  to: `Some big
multiline
text`
}
```

    replace-in-file dist/**/*.html -c replace.js

Thoughts?

**Comment by adamreisnz** [comment]
@RyanZim yeah that sounds useful, it would also solve the issue of being able to specify array values. I'd call the config flag `--config` to be explicit though. Would you like to create a PR for it?

**Comment by RyanZim** [comment]
Yeah, I'd be willing to make a PR when I get time. If someone beats me to it, that's fine.

**Comment by adamreisnz** [comment]
Great, thanks. If I get around to it before you I'll let you know.

**Comment by RyanZim** [comment]
PR done: #16.
