### ISSUE TITLE
any esm support or json config?

### ISSUE THREAD

**Issue by viT-1** [adamreisnz/replace-in-file#150]
Thank you for your module. I use your module [in package.json scripts](https://github.com/viT-1/dist-gh-pages/blob/7b9cf0a1902e262b4cd0aa9760b3a99e68bd8816/package.json#L19):
`"scripts": { "replacestr": "replace-in-file ./dist/index.html --configFile=./replace-in-file.config.js" }`
On modern way node can use esm scripts. Are you planning to add support esm export configs or json?

**Comment by adamreisnz** [comment]
Yes, I will try to convert this package to an ESM module for version 8

**Comment by FreePhoenix888** [comment]
Are there any news?

**Comment by adamreisnz** [comment]
I will work on this in the coming days 🎉

**Comment by adamreisnz** [comment]
Sorry for the delay! This has now been implemented and will be released shortly.
