### ISSUE TITLE
glob may as  a peer dependency.

### ISSUE THREAD

**Issue by Rabbitzzc** [adamreisnz/replace-in-file#152]
In fact, many projects has installing glob packages, and glob package are not needed when glob is turned off（disabledGlob）. Therefore, I personally believe that Glob can be used as a peer dependencies

**Comment by adamreisnz** [comment]
It is a problem because if we do use glob, we need a specific version, as the latest versions have changed and the package hasn't been updated to support them. Therefore, we prefer to use glob as a direct dependency for now to be able to lock in the exact version.
