### ISSUE TITLE
Does not follow symlinks (anymore)?

### ISSUE THREAD

**Issue by nextgenthemes** [adamreisnz/replace-in-file#155]
I am not sure if it worked in the past, I think it did. If it has anything to do with node version or this package, but it does not work when I point it to a relative path in a symlinked directly.

I also switched from SUSE to Ubuntu and from ext4 to ZFS, but I do not think that is the cause.

It works (again) if I use an absolute path.

**Comment by adamreisnz** [comment]
This package uses the Node native `fs.readFileSync` and `fs.readFile`, so if any symlinks are not working that is likely an environmental issue, not related to this package specifically.
