### ISSUE TITLE
Upgrade brace-expansion/1.1.11 and node-concat-map/0.0.1 as they are >5 years old versions

### ISSUE THREAD

**Issue by RajuGuptaGkp** [adamreisnz/replace-in-file#159]
Hello Team,

Please upgrade below components as they are more than 5 years old - 

1.brace-expansion/1.1.11 and 
2. node-concat-map/0.0.1

Thanks,
Raju

**Comment by adamreisnz** [comment]
We don't use these components directly in this library. I suggest you ask
the libraries where these components are direct dependencies to update them
there? We don't know what impact updating them will have on the underlying
libs.
