### ISSUE TITLE
Regex in to

### ISSUE THREAD

**Issue by kshitijkurandwad211** [adamreisnz/replace-in-file#166]
Can add a new feature where right now from can be regex and to is supposed to string. 
This is causing problems while using typescript but in normal node js. This works wonderfully. Just changing .d.ts can even run regex for replacement.

**Comment by adamreisnz** [comment]
If this is just a Typescript definitions change, then please feel free to create a PR for this and I'll merge it in.

**Comment by adamreisnz** [comment]
PR has been closed as according to the documentation, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace, the replace function only accepts a string or a function, not a regex.
