### ISSUE TITLE
All declarations should be exported

### ISSUE THREAD

**Issue by kukko** [adamreisnz/replace-in-file#172]
Hello!

I got the following error while trying to use from a TypeScript project: "`Individual declarations in merged declaration 'replaceInFile' must be all exported or all local.`"

I tried it out and if simply exporting the replaceInFile namespace, it can solve this issue.

I import the package like this:
`import replace from 'replace-in-file';`

**Comment by adamreisnz** [comment]
Hi there, I don't maintain the Typescript side of things for this package, but you're welcome to open a PR

**Comment by kukko** [comment]
You can close this issue, since PR #173 which resolves this, has already been merged. :)
