### ISSUE TITLE
bug when use string replace?

### ISSUE THREAD

**Issue by HaveF** [adamreisnz/replace-in-file#18]
Hi, ;-)

# Original file:
```
a b c d a b c d
```
Option:
```js
  const options = {
    //Single file
    files: 'test',

    //Multiple replacements with the same string (replaced sequentially)
    from: ['a', 'b'],
    to: ['aa', 'bb'],
  }
```
# Result:
```
aa bb c d a b c d
```
It should be
```
aa bb c d aa bb c d
```

I know it can use `/a/g` to replace globally, but sometimes it is easy to use string instead of regex.

**Comment by adamreisnz** [comment]
Hi @HaveF, the `from` and `to` parameters are [fed straight into](https://github.com/adamreisnz/replace-in-file/blob/master/lib/replace-in-file.js#L100) Javascript's `replace` function.

As such, the behaviour is dictated by that function, which states:

> A String that is to be replaced by newSubStr. It is treated as a verbatim string and is not interpreted as a regular expression. **Only the first occurrence will be replaced.**

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace for more details.

So if you want to replace all occurrences, I'm afraid you'll have to use regular expressions or run the command multiple times until no replacements are found.

**Comment by HaveF** [comment]
hi, @adamreisnz thanks for your reply and detailed explanation!

Well, it make sense about the JS original `replace` function, but I suppose it is only used for **short string replacement**---maybe I am wrong.

Btw, what scenario do you think to use replace the first string **in a file**?

Anyway, I know your idea about this :-) Thanks again!

**Comment by adamreisnz** [comment]
Well, I suppose we could add a flag and convert a given string to regex to
make sure it replaces all occurrences, but that counts open a can of worms
I fear... I think it's simpler to just pass in a regex yourself, that way
you have more control as well.

**Comment by HaveF** [comment]
I just find it is very easy to generate regex from string like this `new RegExp('ab.c', 'g');`
I suppose I had to rewrite all strings...

Ok, all done:-)

**Comment by adamreisnz** [comment]
👍
