### ISSUE TITLE
Pass filename to custom processors

### ISSUE THREAD

**Issue by ITDancer13** [adamreisnz/replace-in-file#185]
I've got some use cases where I need to know which file is currently handled by a custom processor. Unfortunately the filename is not passed but it's almost there (see https://github.com/adamreisnz/replace-in-file/blob/main/lib/helpers/run-processors.js).

Would you like to see a PR  for that or does approach not fit to the idea of the lib?

**Comment by ITDancer13** [comment]
I've created a PR for this. Please let me know if I have to adjust it somehow: https://github.com/adamreisnz/replace-in-file/pull/186

**Comment by adamreisnz** [comment]
Thanks, it looks good, I have left a few suggested tweaks but once those are done I can approve and release this feature.
