### ISSUE TITLE
inflight (glob v8) security vulnerability: Missing Release of Resource after Effective Lifetime

### ISSUE THREAD

**Issue by lemke-ethan** [adamreisnz/replace-in-file#187]
There is a security vulnerability in glob v8's dependency of inflight. See this [snyk link](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116) for more info.

If glob is upgraded to v9 the vulnerability will be resolved. 

It does that appear that the synchronous API of replace-in-file is affected by this vulnerability.

**Comment by adamreisnz** [comment]
Hi, thanks for reporting. I am working on converting the module to ESM and this will include a new version of Glob. Will be released as 8.0.0 shortly.
