### ISSUE TITLE
capturing groups

### ISSUE THREAD

**Issue by tonywoode** [adamreisnz/replace-in-file#19]
unless i'm mistaken, it is not possible to specify a capturing group in 'from:` and reference it in 'to:' - a showstopper in many circumstances - am I right, or just doing it wrong? thanks...

**Comment by adamreisnz** [comment]
You might be using it incorrectly. I've added a test to demonstrate that this works:

https://github.com/adamreisnz/replace-in-file/blob/master/lib/replace-in-file.spec.js#L125-L135

See also here for more details on usage: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

**Comment by tonywoode** [comment]
thank you for the information and the unit test, I can see I was just doing it wrong, sure. Much appreciated! I'll let you know if I find any real issues as I go..

**Comment by adamreisnz** [comment]
No problem, thanks!
