### ISSUE TITLE
Is there a way to represent empty?

### ISSUE THREAD

**Issue by xiasun** [adamreisnz/replace-in-file#198]
For example I want to remove all variables with suffix `_2` with empty in my file
```
replace-in-file /_2/g '' my-file.js
```
But I can't a proper way to represent empty, Is there any?

Thanks~

**Comment by adamreisnz** [comment]
Yes, I suggest instead of using the `to` parameter, you use a local `.json` [config file](https://github.com/adamreisnz/replace-in-file/blob/main/README.md#cli-usage) instead:

`replace-in-file my-file.js --configFile=config.json`

config.json
```json
{
  "from": "/_2/g",
  "to": "",
}
```

You can put the `my-file.js` in your config as well.

**Comment by xiasun** [comment]
Thanks, using config file is fine!
