### ISSUE TITLE
Option switch of "replace" to "from" and "with" to "to" fails to log 

### ISSUE THREAD

**Issue by pettyron** [adamreisnz/replace-in-file#20]
In the options when switching from this as suggested in the console:

Option `replace` is deprecated. Use `from` instead.
Option `with` is deprecated. Use `to` instead.

console.log('Modified files:', changedFiles.join(', '));

No longer lists the changedFiles to the console. If I switch it back to `replace` and `with` it then lists the changedFiles again.

I'm using a promise but I've tried every single method and it still doesn't work. 

I'm using replace-in-file 2.5.0

************
My code:
************
    const stripOptions = {
    	files: [
    		'htdocs/160/index.html',
    		'htdocs/300/index.html',
    		'htdocs/600/index.html',
    		'htdocs/728/index.html'
    	],
    	replace: '<script id="__bs_script__">//<![CDATA[\ndocument.write("<script async src=\'http://HOST:3000/browser-sync/browser-sync-client.js?v=2.17.2\'><\\/script>".replace("HOST", location.hostname));\n//]]></script>',
    	with: ''
    }
    gulp.task('snippetInject', () => {
    	replace(injectOptions)
    		.then(changedFiles => {
    			console.log('BrowserSync Snippet successfully injected into:', changedFiles.join(', '));
    		})
    		.catch(error => {
    			console.error('error occurred:', error);
    		});
    });

**Comment by pettyron** [comment]
Actually the only issue on my part is copying and pasting mismatched segments from what I'm working with. So do avoid further confusion here is my entire Gulp file to show what I'm doing with replace-in-file. I'm using Browser-Sync to kick off and watch my HTML files while I work. When that starts I inject the snippet into the HTML files and when I hit ctrl-c to exit Gulp I delay the close and strip the snippet back out with replace-in-file.

`//*******************************************************************************
//***           MMGY Banner Production | Gulp Production File                 ***
//***       Standard Banner Tasks for Standard Four Size Projects             ***
//***                       Core Version: 2.2.3                               ***
//***                      Authors: Ronnie Petty                    		  ***
//***   Repository: https://bitbucket.org/mmgyglobal/production_htmlbanners   ***
//*******************************************************************************

/** Declaring const because we don't want values to change */

const gulp = require('gulp'),
	runSequence = require('run-sequence').use(gulp),
	del = require('del'),
	fs = require('fs'),
	zip = require('gulp-zip'),
	phantom = require('gulp-phantom'),
	replace = require('replace-in-file'),
	replaceBatch = require('gulp-html-replace'),
	browserSync = require('browser-sync').create()
	reload = browserSync.reload;

/**
* Gulp LiveReload has been abandoned as a Project
* Using an abandoned project is risky as NPM will eventually delist and remove the package
* BrowserSync is being used here as its replacement
* LiveReload is available too but it is not the same as the Gulp Plugin
* Between the two, BrowserSync and LiveReload, BrowserSync is better maintained,
* easier to implement, better performing and more customizable for dev environments.
* Easier to implement means that BrowserSync can conform to any build environment i.e. Gulp, Grunt and etc.
* and has set up documentation for said environments.
* LiveReload does not offer the same flexibility and would require some NodeJS dev work to run.
* This could lead to build nightmares for those who are not skilled in NodeJS development.
* For more on BrowserSync:
* @see {@link https://browsersync.io/docs}
* @see browsersync.md
*/

const collectConfig = require('./gulp/config').collectFiles;

const injectOptions = {
	files: [
		'htdocs/160/index.html',
		'htdocs/300/index.html',
		'htdocs/600/index.html',
		'htdocs/728/index.html'
	],
	replace: '',
	with: '<script id="__bs_script__">//<![CDATA[\ndocument.write("<script async src=\'http://HOST:3000/browser-sync/browser-sync-client.js?v=2.17.2\'><\\/script>".replace("HOST", location.hostname));\n//]]></script>'
}

const stripOptions = {
	files: [
		'htdocs/160/index.html',
		'htdocs/300/index.html',
		'htdocs/600/index.html',
		'htdocs/728/index.html'
	],
	replace: '<script id="__bs_script__">//<![CDATA[\ndocument.write("<script async src=\'http://HOST:3000/browser-sync/browser-sync-client.js?v=2.17.2\'><\\/script>".replace("HOST", location.hostname));\n//]]></script>',
	with: ''
}

function getTask(task) {
	return require('./gulp/' + task)(gulp);
}

gulp.task('styles', getTask('stylesTasks'));
gulp.task('scripts', getTask('scriptTasks'));
gulp.task('images', getTask('imageTasks'));

gulp.task('sprite:300', getTask('imgSprite/medRectPng'));
gulp.task('sprite:160', getTask('imgSprite/skyScraperPng'));
gulp.task('sprite:728', getTask('imgSprite/leaderBoardPng'));
gulp.task('sprite:600', getTask('imgSprite/halfPagePng'));

gulp.task('sprite:300jpg', getTask('imgSprite/medRectJpg'));
gulp.task('sprite:160jpg', getTask('imgSprite/skyScraperJpg'));
gulp.task('sprite:728jpg', getTask('imgSprite/leaderBoardJpg'));
gulp.task('sprite:600jpg', getTask('imgSprite/halfPageJpg'));

gulp.task('snippetInject', () => {
	replace(injectOptions)
		.then(changedFiles => {
			console.log('BrowserSync Snippet successfully injected into:', changedFiles.join(', '));
		})
		.catch(error => {
			console.error('error occurred:', error);
		});
});

gulp.task('serve:files', ['styles', 'scripts', 'snippetInject'], (gulpCallBack) => {
	browserSync.init({
		browser: 'google chrome',
		server: {
	        baseDir: './',
			directory: true
	    },
		startPath: '/htdocs',
		files: ['./htdocs/160/index.html', './htdocs/300/index.html', './htdocs/600/index.html', './htdocs728/index.html'],
		notify: false
	}, function callback() {
		gulp.watch(['htdocs/**/*.html', 'htdocs/**/assets/scripts/*.js'], browserSync.reload);

		gulp.watch('htdocs/**/assets/styles/*.css', () => {
			gulp.src('htdocs/**/assets/styles/*.css')
				.pipe(browserSync.stream());
		});

		gulpCallBack();
	});
});

// Staging task run this to remove the browser-sync snippet and replace it with the placeholder comment for re-use
// This process will happen automatically with a 3 second delay to end the gulp process after hitting CTRL-C
function stageReady () {
	replace(stripOptions)
		.then(changedFiles => {
			console.log('BrowserSync Snippet successfully replaced in:', changedFiles.join(', '));
		})
		.catch(error => {
			console.error('error occurred:', error);
		});
}

//******************************************************************************************
// SPRITES TASK: Run `gulp sprite` | Runs a sequence for Sprites to avoid individual tasks
//******************************************************************************************

gulp.task('sprite', ['sprite:160', 'sprite:300', 'sprite:600', 'sprite:728','sprite:160jpg', 'sprite:300jpg', 'sprite:600jpg', 'sprite:728jpg', 'styles']);

// Just PNG | Run this if you only have PNGs you're spriting
gulp.task('sprite:png', ['sprite:160', 'sprite:300', 'sprite:600', 'sprite:728', 'styles']);

// Just JPEG | Run this if you only have JPEGs you're spriting
gulp.task('sprite:jpg', ['sprite:160jpg', 'sprite:300jpg', 'sprite:600jpg', 'sprite:728jpg', 'styles']);

gulp.task('sprite:clean', () => {
	return del([
		'src/scss/partials/_jpg-sprite-160.scss',
		'src/scss/partials/_jpg-sprite-300.scss',
		'src/scss/partials/_jpg-sprite-600.scss',
		'src/scss/partials/_jpg-sprite-728.scss',
		'src/scss/partials/_sprite-160.scss',
		'src/scss/partials/_sprite-300.scss',
		'src/scss/partials/_sprite-600.scss',
		'src/scss/partials/_sprite-728.scss',
		'src/sprites/jpeg/160x600/*',
		'src/sprites/jpeg/300x250/*',
		'src/sprites/jpeg/300x600/*',
		'src/sprites/jpeg/728x90/*',
		'src/sprites/png/160x600/*',
		'src/sprites/png/300x250/*',
		'src/sprites/png/300x600/*',
		'src/sprites/png/728x90/*'
	]);
});

// Comp Folder if you desire to layout your banners with an image comp
// Make directories for comps and a task to remove them
const ssCompDir = 'htdocs/160/assets/images/comps/',
      mrCompDir = 'htdocs/300/assets/images/comps/',
	  hpCompDir = 'htdocs/600/assets/images/comps/',
	  lbCompDir = 'htdocs/728/assets/images/comps/';

gulp.task('comps:create', () => {
	// Using straight NodeJS to accomplish this since all we want is some folders
	fs.mkdir(ssCompDir, (err) => {
		if (err) {
			return console.error(err);
		}
		console.log('160 comp directory created successfully');
	});
	fs.mkdir(mrCompDir, (err) => {
		if (err) {
			return console.error(err);
		}
		console.log('300 comp directory created successfully');
	});
	fs.mkdir(hpCompDir, (err) => {
		if (err) {
			return console.error(err);
		}
		console.log('600 comp directory created successfully');
	});
	fs.mkdir(lbCompDir, (err) => {
		if (err) {
			return console.error(err);
		}
		console.log('728 comp directory created successfully');
	});
});
// Clean out the comps folders they're only temporary
gulp.task('comps:clean', () => {
	return del([ssCompDir, mrCompDir, hpCompDir, lbCompDir]);
});

//Pre-Collection task remove any extraneous markup
gulp.task ('precollect', () => {
	gulp.src('htdocs/160/*.html')
		.pipe(replaceBatch({
			extraneous: ''
		}))
		.pipe(gulp.dest('htdocs/160/'))

	gulp.src('htdocs/300/*.html')
		.pipe(replaceBatch({
			extraneous: ''
		}))
		.pipe(gulp.dest('htdocs/300/'))

	gulp.src('htdocs/600/*.html')
		.pipe(replaceBatch({
			extraneous: ''
		}))
		.pipe(gulp.dest('htdocs/600/'))

	gulp.src('htdocs/728/*.html')
		.pipe(replaceBatch({
			extraneous: ''
		}))
		.pipe(gulp.dest('htdocs/728/'))
});

// COLLECTION RUNNERS
const project_name = 'project_name';
const project_year = '_YEAR';

gulp.task('zip:160', () => {
	return gulp.src(collectConfig.skyScraper.src)
		.pipe(zip(project_name + '_160x600.zip'))
		.pipe(gulp.dest(project_name + project_year));
});
gulp.task('zip:300', () => {
	return gulp.src(collectConfig.medRect.src)
		.pipe(zip(project_name + '_300x250.zip'))
		.pipe(gulp.dest(project_name + project_year));
});
gulp.task('zip:600', () => {
	return gulp.src(collectConfig.halfPage.src)
		.pipe(zip(project_name + '_300x600.zip'))
		.pipe(gulp.dest(project_name + project_year));
});
gulp.task('zip:728', () => {
	return gulp.src(collectConfig.leaderboard.src)
		.pipe(zip(project_name + '_728x90.zip'))
		.pipe(gulp.dest(project_name + project_year));
});

gulp.task('screenshots', () => {
	return gulp.src('./screenshots.js')
		.pipe(phantom({
			localToRemoteUrlAccess: 'true'
		}))
		.pipe(gulp.dest('./data/'));
});

gulp.task('migrateScreenshots', () => {
	return gulp.src('screenshots/**/*')
		.pipe(gulp.dest(project_name + project_year + '/fallback_images/'));
});

gulp.task('overallClean', () => {
	return del(['./screenshots/', './data/', './artifacts/']);
});

gulp.task('collect', () => {
    runSequence(
    	['zip:160', 'zip:300', 'zip:600', 'zip:728'],
        'screenshots',
        'migrateScreenshots',
        'overallClean'
    );
});

gulp.task('watch', () => {
	gulp.watch('src/scss/**/*.scss', ['styles']);

	gulp.watch('htdocs/**/assets/scripts/*.js', ['scripts']);
});

gulp.task('default', ['watch', 'serve:files'], () => {
	process.on('SIGINT', () => { // When CTRL-C is hit the BrowserSync snippet goes away
		browserSync.exit();
		stageReady();
		console.log(' Removing BrowserSync snippet, Waiting to exit...');
		setTimeout(function () {
			process.exit(2);
		}, 3000); // Delay 3 seconds to let the final task work
	});
}); // Change the default task if you don't want BrowserSync

// gulp.task('default', ['watch']); // Default task sans BrowserSync`

**Comment by adamreisnz** [comment]
Can you please strip the example down to only the replace in file portion so that I can test it locally here?

**Comment by pettyron** [comment]
Absolutely here is the inject task I'm running. If this one is solved then both are.

	// Inject task
	const injectOptions = {
		files: [
			'htdocs/160/index.html',
			'htdocs/300/index.html',
			'htdocs/600/index.html',
			'htdocs/728/index.html'
		],
		replace: '',
		with: '<script id="__bs_script__">//<![CDATA[\ndocument.write("<script async src=\'http://HOST:3000/browser-sync/browser-sync-client.js?v=2.17.2\'><\\/script>".replace("HOST", location.hostname));\n//]]></script>'
	}

	gulp.task('snippetInject', () => {
		replace(injectOptions)
			.then(changedFiles => {
				console.log('BrowserSync Snippet successfully injected into:', changedFiles.join(', '));
			})
			.catch(error => {
				console.error('error occurred:', error);
			});
	});

**Comment by pettyron** [comment]
I actually solved the problem looking at what you did earlier [adamreisnz](https://github.com/adamreisnz).

I switched `console.log('BrowserSync Snippet successfully injected into:', changedFiles.join(', '));` to `console.log('BrowserSync Snippet successfully replaced in:', changedFiles);` and what do you know it's kicking out the changed files into the console. Just taking off the join method did it.

**Comment by pettyron** [comment]
By the way thanks for looking into it. I'm not sure why I didn't think of that in the first place to test it.

**Comment by adamreisnz** [comment]
Cool glad it's resolved, thanks!
