### ISSUE TITLE
Feature request: allow definition of config in .js/.ts files in addition to .json

### ISSUE THREAD

**Issue by fnimick** [adamreisnz/replace-in-file#200]
This would allow for the definition of regex literals rather than relying on the string literal regex detection and parsing behavior.

This would also remove the need for https://github.com/adamreisnz/replace-in-file/issues/199

**Comment by adamreisnz** [comment]
Thanks, if you want support for `.js/.ts` config files, please use an older version of this package, as support for this has been purposely removed in the last major version.
