### ISSUE TITLE
How do I use substring matches with replace-in-file?

### ISSUE THREAD

**Issue by NinjaManatee** [adamreisnz/replace-in-file#21]
I have a `options` object that looks like:

```javascript 
const replaceOptions = {
	files: [
		path.join(distributionDir, "**/*.html")
	],
	from: [
		/<head>/g,
		/<!--\s*(<.*abc-.*)\s*-->/g
	],
	to: [
		str,
		/$1/
	]
};
```

It does the replace, but the lines with the match have the `/` character at the beginning and end of the line. If I leave them off, I get an error that `$1` is not defined.

**Comment by adamreisnz** [comment]
You need to wrap `$1` in a string, as in `'$1'`.

See also the discussion in #19, and this site for more information: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

Also, this unit test:
https://github.com/adamreisnz/replace-in-file/blob/master/lib/replace-in-file.spec.js#L125-L135

**Comment by NinjaManatee** [comment]
Thanks, I didn't see the help so I missed that. 

	
Andy Gardner
Director, Sales Engineering
p: 800.821.8147	m: 540.808.5302
w: chartiq.com	e: andy@chartiq.com

**Comment by adamreisnz** [comment]
No worries!
