### ISSUE TITLE
Document return value

### ISSUE THREAD

**Issue by DanielSWolf** [adamreisnz/replace-in-file#22]
I found this library very helpful! 😄 

However, it isn't obvious from the documentation that there is a return value and what exactly the return value contains. I first thought it returned *all* files contained in the glob expression, and I had to skim the source code to find that it only returns the modified files (which, by the way, was exactly what I needed).

It would be great if you could document the return value!

**Comment by adamreisnz** [comment]
Hi @DanielSWolf, thanks, glad you find it useful!

I've updated the documentation to more explicitly provide information about the return value. Thanks for the suggestion.

**Comment by DanielSWolf** [comment]
👍
