### ISSUE TITLE
cannot match an entire line in a text file

### ISSUE THREAD

**Issue by dutu** [adamreisnz/replace-in-file#23]
Hi, I'm trying to replace an entire line (that starts with a specific value) in a text file.
I'm using 
```js
     let options = {
        files: 'filename',
        from: /line starting with some text.*/,
        to: ' a new line replacing the old one',
     } 
```
The issue is that there is no match despite the file contains the line
`line starting with some text and something else`

Any suggestions?

**Comment by dutu** [comment]
Sorry it works OK with the example above

**Comment by adamreisnz** [comment]
No worries, let me know if you find anything else.
