### ISSUE TITLE
Find and replace not being applied across multiple files

### ISSUE THREAD

**Issue by udyux** [adamreisnz/replace-in-file#25]
I'm building a CLI tool for applying our various templates when starting a project and one of the features is a find-and-replace for config files. Input is parsed and replace-in-file is given the following directory tree:
```bash
./
  + lib/
  |  + tests/
  |  |  - replace.test.xml
  |  |  + nested/
  |  |  |  - replace-nested.test.json
```
and the following options:
```javascript
let options = {
    from: [ /%email%/g, /%url%/g, /%user%/g, /%pass%/g, /%db%/g, /%index%/g ],
    to: [ 'test@test.com', 'test.com', 'test', '7357', '_test', false ],
    files: [ 'lib/tests/*.xml', 'lib/tests/**/*.json' ]
}
```
_Note:_ I also tried with a `files` value of `lib/tests/**` and `lib/tests/**/*` with the same result

The output "changed files" array is `[ 'lib/tests/replace.test.xml' ]` and none of the replacements are applied to `lib/tests/nested/replace-nested.test.json`.

Maybe I misunderstood the way the glob is interpreted but I assumed it would capture all matching files. It seems to only catch the closest matching file.

**Comment by adamreisnz** [comment]
Thanks for the report, I'll look into it shortly

**Comment by adamreisnz** [comment]
Peculiar, what operating system are you running this on?

I have just tested with your exact setup and it seems to work fine.

Setup: 
![image](https://user-images.githubusercontent.com/490562/29388943-705c9820-833b-11e7-8a8a-5aa874da7932.png)

Code:
```js
'use strict';

const replace = require('replace-in-file');
const options = {
  from: [ /%email%/g, /%url%/g, /%user%/g, /%pass%/g, /%db%/g, /%index%/g ],
  to: [ 'test@test.com', 'test.com', 'test', '7357', '_test', 'false' ],
  files: [ 'lib/tests/*.xml', 'lib/tests/**/*.json' ]
};

replace(options)
  .then(changed => {
    console.log(changed);
  })
  .catch(error => {
    console.error(error);
  });
```

Output after running:

```sh
node index.js
[ 'lib/tests/replace.text.xml',
  'lib/tests/nested/replace-nested.test.json' ]
```

Contents:

![image](https://user-images.githubusercontent.com/490562/29388988-ad40bb40-833b-11e7-8c2c-1a77cb158d14.png)

**Comment by udyux** [comment]
I recreated the setup outside the project and everything works as expected. I'll go over my options parsing and let you know what's going on but it now seems likely that the issue is in my code.

Thanks for the quick response.

**Comment by udyux** [comment]
Figured it out. I'm a front-end dev by day and this is my first Node for CLI project, still navigating the file system gotchas.

The script receives a `sources` object and a `greps` array which is received from prompt inputs. The keys in `sources` are globs and their values are the number of `greps` that belong to it. This makes it possible to scope the replacements all while allowing two scopes to overlap.

In the test case I provided, `lib/tests/nested/replace-nested.test.json` was also being scoped by a second replacement set. The function went something like this:
```javascript
return Promise.all(Object.keys(sources).map(src => {
  let from = []
  let to = []
  let files = src.replace(/^\//, '')
  let scope = greps.splice(0, sources[src])

  scope.forEach(([grep, sub]) => {
    from.push(eval(`/${placeholder + grep + placeholder}/g`))
    to.push(sub)
  })

  return replace({ files, from, to, allowEmptyPaths: true })
}))
```

Essentially, running this async was preventing the nested file from being accessed by one of the two replacements. Switching to a sync pattern works perfectly.
```javascript
let changeset = []

Object.keys(sources).forEach(src => {
  let from = []
  let to = []
  let files = src.replace(/^\//, '')
  let scope = greps.splice(0, sources[src])

  scope.forEach(([grep, sub]) => {
    from.push(eval(`/${placeholder + grep + placeholder}/g`))
    to.push(sub)
  })

  changeset.push(replace.sync({ files, from, to, allowEmptyPaths: true }))
})

return Promise.resolve(changeset)
```

Closing the issue as the issue was me.

**Comment by adamreisnz** [comment]
Awesome, glad you found the issue!
