### ISSUE TITLE
Hashmark

### ISSUE THREAD

**Issue by robsonsobral** [adamreisnz/replace-in-file#31]
Hi!

Is it possible to use `replace-in-file` with [`hashmark`](https://github.com/keithamus/hashmark)? There was a [package for it](https://github.com/songkick/replaceinfiles/tree/master/examples/hashmark), but it's deprecated now.

Thank you!

**Comment by adamreisnz** [comment]
Well, this is just a standalone tool. We're not looking to integrate explicitly with other packages, but you can of course use the package in a build script like npm scripts or something like Gulp.

Here's a simple example of how to create a gulp task using replace-in-file for example:

```js
'use strict';

/**
 * Dependencies
 */
const path = require('path');
const replaceInFile = require('replace-in-file');
const build = require('../build');
const config = require('../config');

/**
 * Update redirects
 */
module.exports = function updateRedirects(done) {
  replaceInFile({
    files: path.join(build.DEST_ASSETS, '_redirects'),
    from: /%API_BASE_URL%/g,
    to: config.API_BASE_URL,
  }, done);
};
```

**Comment by robsonsobral** [comment]
Thank you for your attention.

Hashmark outputs tis modification to `stdout`. I was thinking on use that. I gonna have to code a scritpt to change the output format. A sample:

```json
{
  "static/dist/css/index-legacy.css": "public_html/static/dist/css/index-legacy-8c574c6c.css",
  "static/dist/css/qa.css": "public_html/static/dist/css/qa-e1006519.css",
  "static/dist/css/index.css": "public_html/static/dist/css/index-f4c7f0f8.css"
}
```

Thank you!

**Comment by adamreisnz** [comment]
No worries, good luck.
Maybe the deprecated plugin could give you some idea's on how to approach it.

I seem to recall having used hashmark in the past before, but I didn't quite like the way it outputted data now that you mention it.

**Comment by robsonsobral** [comment]
May I ask which path you took, instead of using hashmark?

**Comment by adamreisnz** [comment]
Couldn't tell you anymore, it was for a client I contracted for and I think in the end we just didn't use it.

Nowadays I don't use hash tags for this purpose anyway, because I host most my client apps on Netlify, which comes with a CDN that automatically purges the cache when you redeploy, so there generally aren't any caching issues. 

That, in combination with just applying a version suffix to my js/css files works well.

**Comment by adamreisnz** [comment]
Closing this now, but let me know if you need any more help with replace-in-file!
