### ISSUE TITLE
Glob error with windows UNC Paths

### ISSUE THREAD

**Issue by Ebsy** [adamreisnz/replace-in-file#32]
Hi, trying to use a Windows UNC path in 'files' e.g. 
{'files': '//SERVER/share/directory/file.txt'}

replace-in-file returns an error that no file exists with this glob pattern.
using fs.access for this path is no problem. I believe it is an issue with node-glob.

Would it be possible for replace-in-file to contain an option to not use glob if the file doesn't contain regex wildcards?

**Comment by adamreisnz** [comment]
Sure, I'll look into that later today!

**Comment by adamreisnz** [comment]
I'll implement this in 3.0.0 under a flag `useGlobs: false`
That seems the safest way to disable globs, instead of testing the strings.

**Comment by adamreisnz** [comment]
@Ebsy could you give `3.0.0-beta.1` a try using the `disableGlobs: true` parameter?

See https://github.com/adamreisnz/replace-in-file/releases/tag/v3.0.0-beta.1

**Comment by Ebsy** [comment]
Perfect! working as expected.
Thanks Adam. I'll go ahead and close it.
