### ISSUE TITLE
Unable to install replace-in-file package

### ISSUE THREAD

**Issue by maranranu** [adamreisnz/replace-in-file#35]
While trying to install replace-in-file package it gives me a error 
npm ERR! Cannot read property '0' of undefined
node version: 8.5.0
npm version: 5.3.0

**Comment by adamreisnz** [comment]
That looks like an issue with npm perhaps. Can you update both Node and npm to the latest version and try again? I haven't heard any other reports like this and no changes have been made to the package recently.

Are you trying to install a specific version or just the latest?

**Comment by adamreisnz** [comment]
I'll close this off now, if you've still got issues let me know.
