### ISSUE TITLE
Number of matches

### ISSUE THREAD

**Issue by mkaragol64** [adamreisnz/replace-in-file#38]
Hi @adamreisnz 

Is it possible to get total number of matches in all files? Or number of total matches file by file? Or both?

**Comment by adamreisnz** [comment]
Hi @mkaragol64, this is not currently possible, but if someone can tame the [replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method [implementation](https://github.com/adamreisnz/replace-in-file/blob/master/lib/helpers/make-replacements.js#L43) in this library to report on how many replacements were made then it should be doable.

Will leave this open for PR's, as I don't have the time to look into it myself at the moment.

**Comment by jschuman** [comment]
Is this just a question of using the [match](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) method to count and accumulate the number of matches _prior_ to calling replace?  A good reference point is [here](https://stackoverflow.com/questions/1072765/count-number-of-matches-of-a-regex-in-javascript).

**Comment by adamreisnz** [comment]
It would be yes, but I am worried if that might impact performance for large scale replacements. Perhaps it could be enabled and counted only if a flag was passed and set to `true`.

In addition, currently the library returns an array of files that were changed. If we need to return any other information as well, this would be a breaking change and we'd have to look at returning a result object with various properties.

**Comment by adamreisnz** [comment]
Implemented in 4.0.0
