### ISSUE TITLE
Add prefix

### ISSUE THREAD

**Issue by stephane-r** [adamreisnz/replace-in-file#41]
Hello @adamreisnz :)

Is it possible to add prefix in place to replace ?

For example :

replace `test.png` to `/custom/path/test.png` ?

Thank you !

**Comment by adamreisnz** [comment]
Yes that's no problem, you can use regular expressions or a function to make replacements, as we use [String.prototype.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) under the hood.

Try something like:

```js
const options = {
  files: 'path/to/file',
  from: /([a-z-]+\.png)/g,
  to: '/custom/path/$1',
};
```

or

```js
const options = {
  files: 'path/to/file',
  from: /[a-z-]+\.png/g,
  to: (match) => `/custom/path/${match}`,
};
```

Untested, but you'll get the idea!

**Comment by stephane-r** [comment]
Thank you @adamreisnz !
