### ISSUE TITLE
Differentiate between not matched and not replaced

### ISSUE THREAD

**Issue by jlenos** [adamreisnz/replace-in-file#42]
I want to be able to tell if a value was matched but not replaced due to the replacement being an identical string. This is in the context of my attempts to do key/value overrides with more specific error handling.

**Comment by CxRes** [comment]
On a related note, is it possible to request a list of files where matches were not found?

**Comment by adamreisnz** [comment]
This original issue also would need breaking changes to the API, so that we can return a more complex data structure as the result of replacements, with more information about what was replaced and what wasn't.

**Comment by adamreisnz** [comment]
Implemented in 4.0.0
