### ISSUE TITLE
Dry run support

### ISSUE THREAD

**Issue by maxime1992** [adamreisnz/replace-in-file#44]
When using this, instead of modifying to file I'd like to have a dry run which does not modify anything.

Maybe just returning the result to the output.

This would allow me to do some testing too :+1: 

Thanks for the lib it's great! :clap:

**Comment by adamreisnz** [comment]
[Done](https://github.com/adamreisnz/replace-in-file#dry-run), let me know if this helps!

**Comment by maxime1992** [comment]
Well that was fast :tada: !

Thanks a lot I'll give a try tomorrow

**Comment by maxime1992** [comment]
Just tried it, perfect :ok_hand: 

Cheers
