### ISSUE TITLE
Return List of Files where replacements are not made

### ISSUE THREAD

**Issue by CxRes** [adamreisnz/replace-in-file#45]
As discussed in #42, is it possible to request a list of files where matches were not found?

My use case involves replacing copyright/license headers in source code files and if such a header is not found the same is reported.

**Comment by adamreisnz** [comment]
This would actually have to introduce a breaking change so that we can return a more complicated results set, not just an array of changes.

I will put it on the list for the next major version.

**Comment by adamreisnz** [comment]
Implemented in 4.0.0

**Comment by CxRes** [comment]
Thank you!!!!!

**Comment by adamreisnz** [comment]
No worries, sorry it took a while! :)
