### ISSUE TITLE
Can't ignore node_modules when search/replace

### ISSUE THREAD

**Issue by xavortm** [adamreisnz/replace-in-file#48]
Hey, I have been struggling for about an hour to ignore completely node_modules folder. My setup is very basic - a WordPress theme, it has node_modules inside, it also has a script for search and replaces where I want to change all occurrences of a string. 

Here is my basic script setup:

```
const options = {
	files: "./**/*",
	from: /themename/g,
	to: answers.project.local,

        // just the different patterns I tested
	ignore: [
		"node_modules/**/*",
		"node_modules",
		"./node_modules/",
		"./node_modules/*",
		"../node_modules"
	]
};

try {
	const changes = replace.sync(options);
	console.log("Modified files:", changes.join(", "));
} catch (error) {
	console.error("Error occurred:", error); // this fires for files inside node_modules/
}
```

My goal: search and replace all files inside the theme. I am calling the script from the root of the theme, the script above is located in a folder like this: theme/folder/script.js where node modules is in theme/node_modules/ 

I tried all the patterns above, none of them were ignoring and the search and replace takes about 10-15 seconds per run. I have only 150 files or so to check, it should be way faster. I also get errors for files inside node_modules.

I just can't ignore it, no matter what I tried, any advice?

Lastly, how do I also ignore the file the script is in? Because after run, it also changes my 'find' string :D Thanks!

**Comment by adamreisnz** [comment]
Thanks for reporting, it should work, I'll give it a go tomorrow.

**Comment by adamreisnz** [comment]
Looks like this is an issue with Glob, see https://github.com/isaacs/node-glob/issues/309

If you replace `files: "./**/*",` with `files: "**/*",` it works as expected!

**Comment by xavortm** [comment]
Works for me, thanks ^^
