### ISSUE TITLE
How to insert "from" value that contains forward slashes like URL with the "/g" condition

### ISSUE THREAD

**Issue by idanSirin** [adamreisnz/replace-in-file#49]
Hi guys,
I want to change some URL value inside a conf file with another value.
I can't use the regular expression condition because it doesn't define it as a string when I trying to type -   from: ['/http://blabla.com/g']

And I want to replace a multiple values inside the file that contains forward slashes like in the example above.

Do you any solution for it?

Thanks.

**Comment by adamreisnz** [comment]
Hi @idanSirin , you should be able to simply escape the slashes, like so:

`'/http:\/\/blabla.com/g'`

Alternatively, you can also use the new Regexp constructor, see also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

Hope this helps!
