### ISSUE TITLE
Reference capture group in to: with callback

### ISSUE THREAD

**Issue by jschuman** [adamreisnz/replace-in-file#50]
Not sure how/if I can reference a capture group when using the callback version of to:

For example:
```
const options = {
  files: 'path/to/file',
  from: /first:([\w]+)/,
  to: (match) => `first name is: ${match[1]}`
};
```
Am I doing something wrong or is this not currently supported?
Thanks!

**Comment by adamreisnz** [comment]
I think you need to use `$1` in your replacement string to match groups.
See also: 

https://github.com/adamreisnz/replace-in-file/issues/39
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

E.g. this should work (untested):

```
const options = {
  files: 'path/to/file',
  from: /first:([\w]+)/,
  to: `first name is: $1`,
};
```

Let me know if that helps!

**Comment by jschuman** [comment]
Yes, that would work, but I need to use the callback version of the **to:** to interject some logic specific for each found string.

**Comment by jschuman** [comment]
Aha!  Using the ...args option for the callback provides the capture groups (as well as some more information).  So what I can do is this:

`const options = {
  files: 'path/to/file',
  from: /first:([\w]+)/,
  to: (...args) => `first name is: ${args[1]}`
};`

I will close this issue.

**Comment by adamreisnz** [comment]
Brilliant, thanks
