### ISSUE TITLE
Not able to store the attribute for from property in a variable

### ISSUE THREAD

**Issue by mandy8055** [adamreisnz/replace-in-file#52]
Hi All,
Below is my code:
```
let fs = require('fs');
let replaceInFile = require('replace-in-file');

//Define options
var smokeExamples = 'Examples:\n| username  | password  |\n| username1 | password1 |';
var FILE_LOCATION = 'one_folder/abc.feature';
const options = {
  files: ['one_folder/abc.feature',],
  from: /Examples:/g,
  to: smokeExamples,
};
fs.readFile(FILE_LOCATION, function (err, data) {
  if (err) throw err;
  if (data.indexOf(smokeExamples) >= 0) {
    options.from =  smokeExamples;
    options.to = 'Examples:';
    console.log('Hello There!!!!');
  }
  console.log('Hi There');
  try {
    const changes = replaceInFile.sync(options);
    console.log('Modified files:', changes.join(', '));
  }
  catch (error) {
    console.error('Error occurred:', error);
  }
});
```
This is my file:
```

Scenario:Hello there I am ABC

Examples:

Scenario: Hello There I am XYZ

Examples:

Scenario: Hello There My name is BCD

Examples:
```

I am trying to implement this code but the condition inside if doesn't seem to work **Properly**. By **Properly** I mean to say that only one time it is replacing the text in the file. Also, if I am trying to append `/g` in my `options.from` property like `options.from = '\/' + smokeExamples + '\/g';` this is also not working to replace all the matching Strings in the file. Please provide some help on how can I replace the text in the file globally by storing the text to be replaced in a variable.

Thanks

**Comment by adamreisnz** [comment]
Try the following to construct a regular expression that will replace globally:

```js
const from = new RegExp(smokeExamples, 'g');
```

**Comment by jschuman** [comment]
Hi, I've been using this package successfully for a bit now and would like to help.  One thing you can do is simplify your example and it would be easier to parse what you are doing.  Specifically:
- Not sure why you're using the fs package to read the file?  Using the 'files' option should suffice and you can remove the readFile code.
- It's not clear to me why you have this code:
```
if (data.indexOf(smokeExamples) >= 0) {
    options.from =  smokeExamples;
    options.to = 'Examples:';
    console.log('Hello There!!!!');
 }
```
Is it just to 'undo' what you've done in previous runs to test again?  If so, you should probably just remove it to avoid confusion when asking the question here.

- If you're saying the offending code is this:
`options.from =  smokeExamples;`
then, yes, Adam's syntax for creating a RegExp object is what you want.

Good luck!

**Comment by adamreisnz** [comment]
Thanks @jschuman !
