### ISSUE TITLE
Error with Either String or RegEx

### ISSUE THREAD

**Issue by yuschick** [adamreisnz/replace-in-file#54]
Hello,

I am trying to use this library via its CLI.

```
"scripts": {
    ...
    "replace": "replace-in-file --configFile=replace-config.js"
}
```

My config file looks like this:

```
const replace = require('replace-in-file');

const options = {
  files: '/sitemap.xml',
  from: /\?>$/,
  to: `?>
  <?xml-stylesheet type="text/xsl" href="/sitemap-template.xsl"?>
  `,
};

replace(options);
```

However, when running that I receive an error.

```
throw new Error('Must specify string or regex to replace');
```

Whether I provide a regex or string in the `from` property, I continue to receive the error. Am I doing something wrong in the config file?

**Comment by yuschick** [comment]
Found my answer here: https://github.com/adamreisnz/replace-in-file/issues/37

**Comment by adamreisnz** [comment]
Yep, I reckon the issue was that the configuration file wasn't exporting a JSON/JS object? 👍
