### ISSUE TITLE
Callback is never called and Promise is also never resolved

### ISSUE THREAD

**Issue by kamesh95** [adamreisnz/replace-in-file#58]
I am using replace-in-file module for replacing text in multiple files in my directory. It works fine in local but when I deploy my app to azure, it never resolves the promise. I even tried with the callback mode which also does not work. This in turn takes up the CPU usage to 100% because I think it is kind of lost somewhere in between forever. Let me know if anyone can help. Thanks.

```const replace = require('replace-in-file');
        const options = {
            files: ['./assets/**/**.*', './assets-admin/**/**.*', './**.html'],
            from: new RegExp('(' + process.env.CDN_LINK + ')?([.]?[.]?\/?[.]?[.]?\/?(assets\/))', 'g'),
            to: function (match) {
                if (!match.startsWith(process.env.CDN_LINK)) {
                    const splitStr = match.split('assets');
                    let path = '';
                    path = process.env.CDN_LINK + '/assets';
                    return path + splitStr[1];
                } else {
                    return match;
                }
            },
        };
        replace(options, function(error, changes) {
            if (error) {
                return console.error('Error occurred:', error);
            }
            console.info('Modified files: ', changes);
        });```

**Comment by kamesh95** [comment]
Yes, I did try replacing a test file's contents and it turned out to react the same way, callback was not called and it got stuck. I think the issue is indeed with access rights because I am manually trying to edit a file on my deployment and it doesn't allow me to do so. But still the module should throw some proper error related to that. Maybe the module tries to write to the file system again and again instead of throwing error after some retry attempts which might go on increasing the CPU utilization

**Comment by adamreisnz** [comment]
Not sure how to address this. If an error is produced within the Azure environment this should surface either through the app or through your system logs. Replace in file doesn't make an effort to swallow or hide any errors, so anything goes wrong it should be displayed. I am also not sure how it could result in an infinite loop within the package, so my best guess at this stage is that this is an environmental issue somehow and you probably need to do some more debugging in the Azure environment.

If it's an access issue, try accessing folders that you know you have access to and where you can make replacements, see if the script works there. I'd also recommend to have a look at the system logs and see if you can find any clues there.

Unfortunately I don't have much experience with Azure myself, so can't help you much more I'm afraid.

**Comment by kamesh95** [comment]
```
app.get(app.get('routePrefix') + '/api/writeContents', function(req, res, next) {
    const filepath = path.join(__dirname, 'testfile.js');
    fs.writeFile(filepath, 'Hello World!', function (error, fileData) {
        res.send();
    });
});
```

I tried this on my deployment and it was strange that it didn't return and got stuck just like the above case. Now I am assured that the problem is with the access permissions on the deployment and not with the module. Might be an issue with the deployment strategy we use, gonna try changing that. Anyways, Thank you so much for your help :) You can close this issue.

**Comment by adamreisnz** [comment]
Thanks for the update, glad you managed to narrow it down a bit, good luck figuring it out!
