### ISSUE TITLE
fix for EMFILE: too many open files

### ISSUE THREAD

**Issue by bearpeta** [adamreisnz/replace-in-file#73]
Hi,

I run into a "EMFILE: too many open files" error with this library for some reason (I didn't spent time on finding out why) but I could fix this thanks to a recommendation by using the library filequeue instead of "fs" in the files "replace-sync.js" and "replace-async.js". 
I don't know if that's any help for you. If not feel free to close this "issue" again. :-)

**Comment by adamreisnz** [comment]
Hi @bearpeta, thanks for the report and suggestion. At this stage we don't want to add reliance on another 3rd party library, and prefer to stick with `fs`. I haven't heard reports of the EMFILE error before, so perhaps it's something specific related to your environment or the number of files you're trying to change?

**Comment by adamreisnz** [comment]
Feel free to reopen this issue if needed

**Comment by daniele-pelagatti** [comment]
Just FYI, I just encountered this error when trying to use this package in a script which initializes a project replacing a placeholder string with the project name.

It seems that if there are enough files in the glob for "files" then this issue occurs.

**Comment by adamreisnz** [comment]
Is it possible to adapt your parent script to load files in batches, to prevent opening too many files at once?
