### ISSUE TITLE
Enhancement: Add types for use in Typescript

### ISSUE THREAD

**Issue by jonathan-spruce** [adamreisnz/replace-in-file#77]
Currently when using this module in Typescript, you get an error when importing this module, it would be great if you could add a declaration file for this module.

**Comment by adamreisnz** [comment]
If you want to submit a PR and maintain the TypeScript type definitions as we go, I'll be happy to add that in. But I have no interest to work on it myself at this stage unfortunately, as I'm not a big fan of TypeScript and prefer pure Javascript.

**Comment by adamreisnz** [comment]
If anyone could cast their 👀 on the PR (#78) to review that'd be great!
