### ISSUE TITLE
Issue with TypeScript

### ISSUE THREAD

**Issue by JonWallsten** [adamreisnz/replace-in-file#79]
I'm having issues with the new types. Not sure if I'm going something wrong or if there's an error.

```import replaceInFile from 'replace-in-file'```
Result:
`TypeError: replace_in_file_1.default is not a function`

```import * as replaceInFile from 'replace-in-file';```
Result:
`TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("replace-in-file")' has no compatible call signatures.`

Can't destruct the import either since just the interfaces shows up.
Maybe @JonnySpruce can answer this? I saw you made the recent PR.

Edit:
Workaround:
```const replaceInFile = require('replace-in-file');```

**Comment by JonnySpruce** [comment]
Hi, @JonWallsten, in my code I'm using the `import replaceInFile from 'replace-in-file'` syntax and it appears to be working, I'm happy to investigate this and get back to you though.

**Comment by JonWallsten** [comment]
@JonnySpruce That's weird. Not sure why my build is failing then. I guess it's either ts-node or something in my tsconfig. I'll reply tomorrow at work with my config file.

**Comment by JonnySpruce** [comment]
@JonWallsten, for reference this is the contents of my `tsconfig.json`:
```json
{
  "compilerOptions": {
      "module": "commonjs",
      "esModuleInterop": true,
      "target": "es6",
      "noImplicitAny": true,
      "moduleResolution": "node",
      "sourceMap": true,
      "outDir": "out",
      "baseUrl": ".",
      "paths": {
          "*": [
              "node_modules/*",
              "src/types/*"
          ]
      }
  },
  "include": [
      "src/**/*"
  ]
}
```

**Comment by JonnySpruce** [comment]
Just as an update, with a completely fresh TypeScript project using this config I can import and use the module with no issues

**Comment by JonWallsten** [comment]
It's the "esModuleInterop" prop. I misread the Compiler option help page and thought it was the same prop as "allowSyntheticDefaultImports". But what it says is that "allowSyntheticDefaultImports" will default to "esModuleInterop" value. My mistake! Thanks!

**Comment by derbenoo** [comment]
For the people who can't set the `esModuleInterop` property to `true` inside their tsconfig.json, here is a workaround:

```ts
import * as _replace from 'replace-in-file';

// Fix types
const replace = (_replace as unknown) as (
  config: _replace.ReplaceInFileConfig
) => Promise<_replace.ReplaceResult[]>;
```

**Comment by pk359** [comment]
> For the people who can't set the `esModuleInterop` property to `true` inside their tsconfig.json, here is a workaround:
> 
> ```ts
> import * as _replace from 'replace-in-file';
> 
> // Fix types
> const replace = (_replace as unknown) as (
>   config: _replace.ReplaceInFileConfig
> ) => Promise<_replace.ReplaceResult[]>;
> ```

awesome. it works.

**Comment by JonWallsten** [comment]
Seems like this is fixed for real now.

import replaceInFile from 'replace-in-file' no longer works:
```
TS2349: This expression is not callable. Type 'typeof import("replace-in-file")' has no call signatures.
```
Fixed by changing to this:
```
import { replaceInFile } from 'replace-in-file';
```

**Comment by tobiashochguertel** [comment]
@JonWallsten Your answer should be appear in the readme.md, so that new people see this information earlier.

**Comment by adamreisnz** [comment]
Feel free to create a PR with proposed change to the readme. I don't personally like or use TypeScript, so I refrain from making TS changes in the code or explanations in the readme.

**Comment by jackz7** [comment]
will it work in angular ?
