### ISSUE TITLE
Recursively search all files and folders?

### ISSUE THREAD

**Issue by moaiii** [adamreisnz/replace-in-file#80]
Hello!

I can't seem to use normal globs to recursively search all files and folders in a project. Using `/user/name/project/**/*/*.*`, `/user/name/project/**.*` or other variations will only ever search the first level of folders. Is this an expected behaviour?

Any help muchly appreciated! :)

**Comment by adamreisnz** [comment]
Hi there, the plugin uses Glob internally, so as long as your Glob config makes sense it should find all files and folders.

Can you provide a more concrete example with full configuration and file/folder structure + expected results?
