### ISSUE TITLE
Add more info when dry option is true ?

### ISSUE THREAD

**Issue by luctst** [adamreisnz/replace-in-file#91]
Hey  👋

I was thinking when the `dry` option is set to true maybe the results object could contain the changements made to the files(s) ?
For example i used the `dry` option to test if everything is ok but i don't have any visual or something to see if the changes are good ?

Thanks for your work, it's great  🙃

**Comment by adamreisnz** [comment]
Thanks for your suggestion. I don't think this is going to be practical to implement, as it means we'll have to analyse the old contents and somehow compare it to the new contents, figuring out what all the replacements have been.

I don't see any easy way of implementing this, as we are not returned a list of changes by the Javascript `replace` method. Tracking it manually and somehow reporting on it would be quite tricky.

At the moment we just report if a file would have been changed or not, as well as the number of matches and replacements. That should be enough for debugging purposes in a dry run I think.

Will leave this open for a while to see if anyone comes up with an idea on how to tackle this.

**Comment by luctst** [comment]
Okay i see i'll try to think about it.

Thanks  🙂

**Comment by adamreisnz** [comment]
Closing this for now, but feel free to reopen if any ideas come up.
