### ISSUE TITLE
Add more info recursive file search cli vs config file

### ISSUE THREAD

**Issue by taylorjdawson** [adamreisnz/replace-in-file#94]
When using the cli the glob pattern is handled by the os. But specifying the glob pattern in the `replace-config.js` file uses the [glob](https://www.npmjs.com/package/glob) module thus warrants different behaviour for the same pattern.  

### Example:

This looks only at top level files
```
// replace-config.js
module.exports = {
  dry: true,
  from: /cat/g,
  to: 'dog'
}
```
```
❯ replace-in-file **  --configFile=replace-config.js
```

However, this is recursive:
```
// replace-config.js
module.exports = {
  dry: true,
  files: '**',
  from: /cat/g,
  to: 'dog',
}
```
```
❯ replace-in-file  --configFile=replace-config.js
```

If you want to use do recursive file search as an argument one must do this:
```
❯ replace-in-file $(ls l {,**/}*)  --configFile=replace-config.js
```

Just thought that I would point that out. It could be useful to document this fact.

It also might be related to #80

**Comment by adamreisnz** [comment]
Thanks for raising this, if you'd like to add a few lines to the readme to document this that'd be great 👍

**Comment by taylorjdawson** [comment]
Would you like this underneath the **CLI Usage** section as a note?

**Comment by adamreisnz** [comment]
Yes, sounds good. Or if it's a lot of text with maybe an example or two, it could warrant it's own subsection, something like "A note on using globs". Thanks!

**Comment by adamreisnz** [comment]
Added it to the readme
