### ISSUE TITLE
Replace an entire string where the text is found

### ISSUE THREAD

**Issue by organnerx** [adamreisnz/replace-in-file#95]
Is there a way to replace an entire string where the needed text is found?
For example I have somewhere in my file "var item = 5335;".

But first, I need to scan for the previous value of this var, and only then use it for searching and replacing.
It will be really good to implement a solution in this module like this:

I search for "var item" and module replaces an entire string where it found for what I need ("var item = 1132;") without checking a previous value first.
Or I search for "var item = *;" and module replaces * for what I need (1132).

Right now I don't see any documentation if this is possible.
Regards.

**Comment by adamreisnz** [comment]
I'm sorry, I don't quite follow what you intend to replace.
You can use a regular expression to replace, so that you don't need to know the value.

For example `/^var item = [0-9]+;$/`

**Comment by organnerx** [comment]
Thank you, that should do the job I need.
