### ISSUE TITLE
Executing replace script from another folder (relative path reference error)

### ISSUE THREAD

**Issue by cbdeveloper** [adamreisnz/replace-in-file#98]
How to execute a script from a different folder and still get correct relative paths using `../someDir`.

Has anyone needed to do this before? This will be a postBuild script at some point.

I have this script that I need to run with `node` through the CLI.

And this script has a file relative file reference as:

```
files: '../functions/index.js',
```

The the file structure is like this:

```
> buildScripts
    myScript.js
> functions
    index.js
```

When I'm inside the `buildScripts` folder (on terminal) everything works:

`>> C:\MyProjectRoot\buildScripts> node myScript.js`

But when I'm inside the `MyProjectRoot` folder, it throws:

`>> C:\MyProjectRoot> node buildScripts/myScript.js`

> **Error occurred:** Error: No files match the pattern: ../functions/index.js

---

**QUESTION**

How can I run this from `myProject` root folder and still get the correct path?

---

I don't know if it depends on the script / packages that I'm running, so here's the full source code for the script:

**myScript.js**

I'm using the `replace-in-file` package to update some imports.

```
const escapeStringRegexp = require('escape-string-regexp');
const fromPath = './src';
const fromPathRegExp = new RegExp(escapeStringRegexp(fromPath),'g');

const replace = require('replace-in-file');
const options = {
  files: '../functions/index.js',  // <----------------------------------
  from: fromPathRegExp,
  to: './distFunctions',
};

replace(options)
  .then(results => {
    console.log('Replacement results:', results);
  })
  .catch(error => {
    console.error('Error occurred:', error);
  })
;
```

**Comment by andywangjs** [comment]
I also ran into this issue where using a relative path doesn't seem to work. I'd like to know if there's something I am doing wrong or relative paths are maybe not supported.

@cbdeveloper I used `path.join(__dirname, your path)` as a workaround for now.

**Comment by cbdeveloper** [comment]
Thanks @andywangjs here's how I've handled it:
https://stackoverflow.com/a/58715451/10128619

I've changed the process cwd with `process.chdir(__dirname); `

```
const path = require('path');
const escapeStringRegexp = require('escape-string-regexp');
const fromPath = './src';
const fromPathRegExp = new RegExp(escapeStringRegexp(fromPath),'g');

const replace = require('replace-in-file');
const options = {
  files: '../functions/index.js',
  from: fromPathRegExp,
  to: './distFunctions',
};

console.log('This is the __dirname: ' + __dirname);
console.log('This is process.cwd(): ' + process.cwd());

process.chdir(__dirname);                         // <--------------------------------
console.log('CHANGED cwd WITH process.chdir');  

console.log('This is the __dirname: ' + __dirname);
console.log('This is process.cwd(): ' + process.cwd());

replace(options)
  .then(results => {
    console.log('Replacement results:', results);
  })
  .catch(error => {
    console.error('Error occurred:', error);
  })
;
```
