### ISSUE TITLE
Replace without modifying the original file

### ISSUE THREAD

**Issue by Muzzamil1** [adamreisnz/replace-in-file#99]
Hi @adamreisnz! 
Can I replace in a file and save it to another location with maybe a different name, without modifying the original file?

**Comment by adamreisnz** [comment]
Hi there, this is currently not possible, but it has a simple work around: simply copy the file to a different location first yourself, and then run replace in file on that copy so the original file remains untouched.

If you'd like to add a copy feature to replace in file you can leave this issue open and I might be able to look into it at a later stage.

**Comment by Muzzamil1** [comment]
Ok
For the time being, I will do as you suggested that copy the file and then run the replace but it will be great to have this feature. 
Thanks

**Comment by adamreisnz** [comment]
Will close this now, but feel free to submit a PR for this feature at some. 

For anyone picking this up: I imagine it will be quite tricky to handle when replacements are made in multiple files. Therefore, my original recommendation still stands. If copying needs to happen, best to write your own script to do the copying first, and then run replace in file on the copied file.
